# Generated by Django 2.0.7 on 2018-08-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('project', '0002_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loghours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('hours_logged', models.FloatField(null=True)),
                ('required_hours', models.FloatField(null=True)),
                ('pm_approval', models.BooleanField()),
                ('am_approval', models.BooleanField()),
                ('hourly_rate', models.FloatField(null=True)),
                ('is_valid', models.BooleanField()),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLogHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('pm_approval', models.BooleanField()),
                ('am_approval', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.AddField(
            model_name='loghours',
            name='project_loghour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loghours.ProjectLogHour'),
        ),
    ]
