# Generated by Django 2.0.7 on 2018-08-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_manager'),
        ('loghours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLoghour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('pm_approval', models.BooleanField()),
                ('am_approval', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='loghours',
            name='project',
        ),
        migrations.AddField(
            model_name='loghours',
            name='project_loghour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loghours.ProjectLoghour'),
        ),
    ]
