# Generated by Django 2.0.7 on 2018-08-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loghours', '0002_auto_20180809_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghours',
            name='project_loghour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loghours.ProjectLogHour'),
        ),
    ]
